### ISSUE TITLE
Cloudinary Credentials

### ISSUE THREAD

**Issue by arikarim** [CollinsTatang/RailsCapstone#3]
Good job so far my friend 👍 , but It is not a good practice to show your cloudinary credentials as it should be hidden.
You can Create a .env file and put them there as a constants then use them back inside cloudinady.yml

**Comment by CollinsTatang** [comment]
> Good job so far my friend  , but It is not a good practice to show your cloudinary credentials as it should be hidden.
> You can Create a .env file and put them there as a constants then use them back inside cloudinady.yml

Thanks for the correction friend, I have to ignore the file
